# Utiliza Python Slim como base
FROM python:3.9-slim

# Configura el directorio de trabajo
WORKDIR /app

# Copia el resto de los archivos al contenedor
COPY frontend/ /app/

# Instala las dependencias
RUN pip install --no-cache-dir -r frontend/requirements.txt

# Expone el puerto 7860 para Gradio
EXPOSE 7860

# Comando para ejecutar la app de Gradio
CMD ["python", "./frontend.py"]


