version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - BACKEND_URL=http://backend:8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_service
    ports:
      - "7860:7860"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - BACKEND_URL=http://backend:8000

